VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ThisWorkbook"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit

'VERSION: 2022.07.05
'AUTHOR: PABLO GONZALEZ PILA <pablogonzalezpila@gmail.com>

Private Sub Workbook_Open()
' Funciones configuradas para ejecutarse al inicio de EXCEL

    CREATE_SHORTCUTS
'    Debug.Print "Workbook_Open"

End Sub
